var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var TimestampWebpackPlugin = require('timestamp-webpack-plugin');

module.exports = {
    entry: {
        about: path.resolve(__dirname, 'src/js/about_page.js'),
        home: path.resolve(__dirname, 'src/js/home_page.js'),
        contact: path.resolve(__dirname, 'src/js/contact_page.js')
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/assets/',
        filename: "[name].js"
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'shared',
            filename: 'shared.js'
        }),
        new ExtractTextPlugin("styles.css"),
        // to offer global variable for JQuery so that it will be visible to every module
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
        // create a file for time-stamp
        new TimestampWebpackPlugin({
            path: __dirname,
            filename: 'timestamp.json'
        }),
        // create a new banner
        new webpack.BannerPlugin("******\nGenerated by webpack\n******\n")
        
    ],
    watch: true,
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                    options: {
                        "presets": [
                            'env'
                        ]
                    }
                }
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            },
            {
                test: /\.(png|jpg|ttf)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            limit: 100000
                        }
                    }
                ]
            }, {
                test: /\.json$/,
                exclude: /node_modules/,
                use: [
                    { 
                        loader: "json-loader"
                    },
                    {
                        loader: path.resolve('loaders/strip')
                    }
                ]
            }, {
                test: /\.html$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "raw-loader"
                    }
                ]
            }
        ]
    },
    resolve: {
        extensions: ['.js', '.es6']
    }
}